apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2019-07-31T13:51:55Z
  generation: 2
  labels:
    app: krutik
  name: krutik
  namespace: default
  resourceVersion: "3886"
  selfLink: /apis/apps/v1/namespaces/default/deployments/krutik
  uid: 5b58ade6-b39a-11e9-9a25-42010a8e022d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: krutik
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: krutik
    spec:
      containers:
      - image: gcr.io/pe-training/krutik-menkudle@sha256:2e4861775558abfb0274aef8c369ba1c09e3d324bc614ea328bf9be799772e8e
        imagePullPolicy: IfNotPresent
        name: krutik-menkudle-sha256
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-07-31T13:51:57Z
    lastUpdateTime: 2019-07-31T13:51:57Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-07-31T13:51:55Z
    lastUpdateTime: 2019-07-31T13:51:57Z
    message: ReplicaSet "krutik-94bb545b4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
